CREATE TABLE IF NOT EXISTS pipeline (
    oid INTEGER NOT NULL,
    env VARCHAR(6),
    name VARCHAR(32),
    description VARCHAR(128),
    phase VARCHAR(32),
    stage VARCHAR(64),
    source_dataset_id INTEGER,
    target_dataset_name VARCHAR(32),
    target_dataset_description VARCHAR(128),
    target_dataset_phase VARHAR(32),
    target_dataset_stage VARCHAR(32),
    target_dataset_format VARCHAR(32),
    target_dataset_partition_col VARCHAR(32),
    normalize_text_column VARCHAR(16),
    normalize_encoding_sample FLOAT,
    normalize_random_state INTEGER,
    dqa_cache_name VARCHAR(16),
    dqa_n_jobs INTEGER,
    text_wordlist_filepath VARCHAR(128),
    creator VARCHAR(32),
    created BIGINT,
    force TINYINT,
    PRIMARY KEY(oid)
);
