#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : GenAI-Lab-SLM                                                                       #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/dev/flow.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/genai-lab-slm                                   #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Tuesday February 4th 2025 02:35:08 am                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                        PHASES                                                    #
# ------------------------------------------------------------------------------------------------ #
phases:
  dataprep:
    stages:
      preprocess:
        source_config:
          phase: dataprep
          stage: raw
          name: review
          filepath: data/stage/dev/reviews
          dftype: pandas
          file_format: parquet
# ------------------------------------------------------------------------------------------------ #
#                            SENTIMENT ANALYSIS STAGE                                              #
# ------------------------------------------------------------------------------------------------ #
      sentiment:
        source_config:
          phase: dataprep
          stage: tqa
          name: review
          dftype: pandas
          file_format: parquet
        target_config:
          phase: dataprep
          stage: sentiment
          name: review
          dftype: pandas
          file_format: parquet
        tasks:
          sentiment:
            class_name: MergeTask
            module: genailab.flow.dataprep.operators.merge
            params:
              filepath: data/stage/dev/sentiments_dev.csv